# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NamGD.com - Dịch vụ thiết kế đồ họa, website Uy tín - Chất lượng - Chuyên nghiệp
email: contact@namgd.com
description: >- # this means to ignore newlines until "baseurl:"
  NamGD.com cung cấp dịch vụ Thiết kế Website trọn gói với giao diện đẹp, độc đáo, sáng tạo. Hệ thống tính năng website đầy đủ, mang tính ứng dụng cao và phù hợp với từng cá nhân, doanh nghiệp. Với mục tiêu cung cấp nhiều gói sản phẩm phong phú về mẫu mã và các tính năng linh hoạt cho nhiều loại hình Website như giới thiệu công ty, bán hàng, trang tin tức, thương mại điện tử… cùng với kho giao diện phong phú đã được NamGD.com lọc chọn và đúc kết nhằm giới thiệu tới khách hàng với mong muốn có một Website nhanh, đẹp, hiệu quả và giá cả hợp lý.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://namgd.com" # the base hostname & protocol for your site, e.g. http://example.com
lang: vi
future: true
keywords:
  [
    web,
    Website,
    thiết kế web,
    thiết kế website,
    làm web,
    làm trang web,
    thiết kế web chuẩn seo,
    công ty thiết kế website,
    thiết kế website chuyên nghiệp,
    tạo web,
    tạo website bán hàng chuyên ngiệp,
    website giá rẻ,
    giá thiết kế website,
    thiết kế đồ họa,
    giá thiết kế đồ họa,
    thiết kế logo,
    thiết kế banner,
    thiết kế poster,
    Thiết kế profile,
    Thiết kế catalogue,
    Thiết kế brochure,
    Thiết kế Card,
    Thiết kế menu,
    Thiết kế Infographic,
    Thiết kế Poster,
    Thiết kế Standee,
    Thiết kế Landing Page,
    Quản trị và chăm sóc website,
    Chỉnh sửa Video,
  ]
# Build settings
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
